### ISSUE TITLE
module 'ast' has no attribute 'AnnAssign

### ISSUE THREAD

**Issue by vBoykoGit** [emilwallner/Screenshot-to-code#35]
I'm running jupyter on the local version on Windows 10 with python 3.6 and get this error:
```
PS C:\Git\Screenshot-to-code-in-Keras\local> jupyter notebook
Traceback (most recent call last):
  File "c:\users\mount\appdata\local\programs\python\python36\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mount\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Mount\AppData\Local\Programs\Python\Python36\Scripts\jupyter-notebook.EXE\__main__.py", line 9, in <module>
  File "c:\users\mount\appdata\local\programs\python\python36\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\mount\appdata\local\programs\python\python36\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "c:\users\mount\appdata\local\programs\python\python36\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\users\mount\appdata\local\programs\python\python36\lib\site-packages\notebook\notebookapp.py", line 1628, in initialize
    self.init_webapp()
  File "c:\users\mount\appdata\local\programs\python\python36\lib\site-packages\notebook\notebookapp.py", line 1378, in init_webapp
    self.jinja_environment_options,
  File "c:\users\mount\appdata\local\programs\python\python36\lib\site-packages\notebook\notebookapp.py", line 159, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "c:\users\mount\appdata\local\programs\python\python36\lib\site-packages\notebook\notebookapp.py", line 271, in init_settings
    nbextensions_path=jupyter_app.nbextensions_path,
  File "c:\users\mount\appdata\local\programs\python\python36\lib\site-packages\notebook\notebookapp.py", line 1061, in nbextensions_path
    from IPython.paths import get_ipython_dir
  File "c:\users\mount\appdata\local\programs\python\python36\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "c:\users\mount\appdata\local\programs\python\python36\lib\site-packages\IPython\terminal\embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "c:\users\mount\appdata\local\programs\python\python36\lib\site-packages\IPython\core\interactiveshell.py", line 111, in <module>
    _assign_nodes         = (ast.AugAssign, ast.AnnAssign, ast.Assign)
AttributeError: module 'ast' has no attribute 'AnnAssign'
```

**Comment by emilwallner** [comment]
Looks like a jupyter problem: https://github.com/jupyter/notebook
